Repository Hanhae99-final-3team/final-be, pull requests merged in 2022-09, with the labels that each got.

#30 <fix> Item 수정 Method 오류 해결(Image Entity 종속관계 부분 수정)
  src/main/java/com/hanghae/mungnayng/domain/image/Image.java
  src/main/java/com/hanghae/mungnayng/repository/ImageRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
Labels: bug

#32 Develop
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ItemResponseDto.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
  src/main/java/com/hanghae/mungnayng/service/ZzimService.java
Labels: feature, refactoring

#34 Develop
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/controller/ZzimController.java
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ItemResponseDto.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
  src/main/java/com/hanghae/mungnayng/service/ZzimService.java
  src/main/java/com/hanghae/mungnayng/util/TimeUtil.java
Labels: feature, refactoring

#38 Develop
  build.gradle
  src/main/java/com/hanghae/mungnayng/config/SwaggerConfig.java
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/controller/SearchController.java
  src/main/java/com/hanghae/mungnayng/controller/ZzimController.java
  src/main/java/com/hanghae/mungnayng/domain/item/Item.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
Labels: feature, refactoring

#44 SwaggerConfig 수정(version up)
  src/main/java/com/hanghae/mungnayng/config/SwaggerConfig.java
Labels: chore

#48 SwaggerConfig 수정
  src/main/java/com/hanghae/mungnayng/config/SwaggerConfig.java
  src/main/java/com/hanghae/mungnayng/controller/ChatController.java
Labels: chore

#49 41 45 47 issue fix
  src/main/java/com/hanghae/mungnayng/config/SecurityConfig.java
  src/main/java/com/hanghae/mungnayng/controller/MemberController.java
  src/main/java/com/hanghae/mungnayng/domain/member/dto/LoginResponseDto.java
  src/main/java/com/hanghae/mungnayng/service/MemberService.java
Labels: bug, documentation, chore

#55 마이페이지 및 검색 부분 기능 수정 및 추가
  src/main/java/com/hanghae/mungnayng/config/SwaggerConfig.java
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/controller/SearchController.java
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ChartResponseDto.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/repository/SearchRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
Labels: feature, chore

#57 <feat> 카카오 로그인 적용
  src/main/java/com/hanghae/mungnayng/controller/MemberController.java
  src/main/java/com/hanghae/mungnayng/domain/member/Member.java
  src/main/java/com/hanghae/mungnayng/domain/member/dto/KakaoUserInfoDto.java
  src/main/java/com/hanghae/mungnayng/repository/MemberRepository.java
  src/main/java/com/hanghae/mungnayng/service/KakaoService.java
  src/main/java/com/hanghae/mungnayng/service/MemberService.java
Labels: feature

#64 item 조회 메소드 변수 추가 및 내가 본 상품 조회 API 개발
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ItemMainResponseDto.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
Labels: feature, chore

#70 상품 상세 조회 API Response 값 수정
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ItemResponseDto.java
  src/main/java/com/hanghae/mungnayng/repository/MemberRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
Labels: chore

#76 Develop
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/controller/SearchController.java
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ItemResponseDto.java
  src/main/java/com/hanghae/mungnayng/domain/search/dto/ItemSearchResponseDto.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/repository/SearchRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
  src/main/java/com/hanghae/mungnayng/service/ZzimService.java
  src/main/java/com/hanghae/mungnayng/util/Validator.java
Labels: bug, feature, refactoring, chore

#81 내가 조회한 상품 목록 호출 API 수정
  src/main/java/com/hanghae/mungnayng/config/SecurityConfig.java
  src/main/java/com/hanghae/mungnayng/config/SwaggerConfig.java
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/util/aws/CommonUtils.java
  src/main/java/com/hanghae/mungnayng/util/aws/S3uploader.java
Labels: bug

#87 검색어 자동저장 토글 관련 개발
  .gitignore
  build.gradle
  src/main/java/com/hanghae/mungnayng/config/QuerydslConfig.java
  src/main/java/com/hanghae/mungnayng/config/SecurityConfig.java
  src/main/java/com/hanghae/mungnayng/controller/MemberController.java
  src/main/java/com/hanghae/mungnayng/controller/SearchController.java
  src/main/java/com/hanghae/mungnayng/domain/member/Member.java
  src/main/java/com/hanghae/mungnayng/domain/zzim/Zzim.java
  src/main/java/com/hanghae/mungnayng/repository/ImageRepository.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/repository/SearchRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/service/MemberService.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
  src/test/java/com/hanghae/mungnayng/service/SearchServiceTest.java
Labels: feature, chore

#91 동적쿼리 적용으로 게시글 리스트 조회 메서드 통합 구현
  src/main/java/com/hanghae/mungnayng/config/QuerydslConfig.java
  src/main/java/com/hanghae/mungnayng/controller/ItemController.java
  src/main/java/com/hanghae/mungnayng/domain/item/dto/ItemRequestParam.java
  src/main/java/com/hanghae/mungnayng/repository/ItemQuerydslRepository.java
  src/main/java/com/hanghae/mungnayng/repository/ItemRepository.java
  src/main/java/com/hanghae/mungnayng/service/ItemService.java
  src/main/java/com/hanghae/mungnayng/service/SearchService.java
  src/main/java/com/hanghae/mungnayng/service/ZzimService.java
  src/main/java/com/hanghae/mungnayng/util/Validator.java
Labels: feature, refactoring

#96 <feat> 토큰재발급을 위한 reissue함수 추가
  src/main/java/com/hanghae/mungnayng/config/SecurityConfig.java
  src/main/java/com/hanghae/mungnayng/controller/MemberController.java
  src/main/java/com/hanghae/mungnayng/exception/GlobalExceptionHandler.java
  src/main/java/com/hanghae/mungnayng/jwt/JwtConfig.java
  src/main/java/com/hanghae/mungnayng/jwt/JwtExceptionFilter.java
  src/main/java/com/hanghae/mungnayng/jwt/JwtProvider.java
  src/main/java/com/hanghae/mungnayng/repository/RefreshTokenRepository.java
  src/main/java/com/hanghae/mungnayng/service/MemberService.java
Labels: feature
